server:
  port: 8890
spring:
  application:
    name: config-bus
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config-server
      uri: http://localhost:8888/
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/

