server:
  port: 8765
spring:
  application:
    name: service-dbcenters
  profiles:
    include: mybatis,redis,mongo
  devtools:
    restart:
      enabled: true                       #热部署生效
      additional-paths: src/main/java     #设置重启的目录，检索目录(resources/static,resorces/templates)
      #exclude: WEB-INF/**                 #classpath目录下的WEB-INF文件夹内容修改不重启

eureka:
  client:
    service-url:
      defaultZone:  http://admin:admin@localhost:8761/eureka/
      register-with-eureka: true
      #从eureka上检索服务
      fetch-register: true
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true