#数据源 db0,db1
sharding:
  jdbc:
    datasource:
      names: db0,db1
    #db0
      db0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name:  com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/nan?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: 1234
    #db1
      db1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name:  com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/nan?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: 1234
    #水平拆分的数据库配置分库+分表策略  行表达式分片策略
    config:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: id
            algorithm-expression: {id % 2}
      #分表策略，分表取决于id行
        tables:
