server:
  port: 8761

spring:
  application:
    name: service-server
  security:
    basic:
      enable: true #开启HTTP basic认证
    user:
      name: admin
      password: admin

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone:  http://${spring.application.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false #禁用自我保护
