
server:
  port: 8767

spring:
  application:
    name: eureka-zuul

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId:  eureka-ribbon
    api-b:
      path: /api-b/**
      serviceId:  eureka-feign

